<?php

namespace App\Enum;

/**
 * Reference: https://github.com/ocpi/ocpi/blob/release-2.2.1-bugfixes/mod_tokens.asciidoc#144-tokentype-enum.
 */
enum TokenTypeEnum: string
{
    case AD_HOC_USER = 'AD_HOC_USER'; // One time use Token ID generated by a server (or App.) The eMSP uses this to bind a Session to a customer, probably an app user.
    case APP_USER = 'APP_USER'; // Token ID generated by a server (or App.) to identify a user of an App. The same user uses the same Token for every Session.
    case OTHER = 'OTHER'; // Other type of token
    case RFID = 'RFID'; // RFID Token
}
